name: 'ETH/USD Price Feed Action'
description: 'GitHub Action to get the current ETH/USD price via Chainlink'
inputs:
  rpc-node:
    description: 'An ethereum RPC node.'
    required: true
outputs:
  int:
    description: 'Price as integer. E.g. 262569053446'
  price:
    description: 'Price as USD value with decimals. E.g. 2625.69053446'
runs:
  using: 'node12'
  main: 'dist/index.js'
